### PR TITLE
Omit try-except & update test

### LINKED ISSUE #52: Let's remove "Error occured during writing JSONL file"
This is the result of a failing pytest on my side. 

```
    def write_jsonl(self, path, sort_keys=False, indent=None):
        """
        Writes to a jsonl file.
    
        Arguments:
            path: filename
            sort_keys: If sort_keys is true (default: False), then the output of dictionaries will be sorted by key.
            indent: If indent is a non-negative integer (default: None), then JSON array elements members will be pretty-printed with that indent level.
        Usage:
    
        ```python
        from clumper import Clumper
        clump_orig = Clumper.read_jsonl("tests/data/cards.jsonl")
        clump_orig.write_jsonl("tests/data/cards_copy.jsonl")
    
        clump_copy = Clumper.read_jsonl("tests/data/cards_copy.jsonl")
    
        assert clump_copy.collect() == clump_orig.collect()
        ```
        """
    
        try:
            # Create a new file and open it for writing
            with open(path, "x") as f:
                for current_line_nr, json_dict in enumerate(self.collect()):
                    f.write(
                        json.dumps(json_dict, sort_keys=sort_keys, indent=indent) + "\n"
                    )
    
        except Exception:
>           raise RuntimeError("Error occured during writing JSONL file")
E           RuntimeError: Error occured during writing JSONL file

clumper/clump.py:276: RuntimeError
```

The message `Error occured during writing JSONL file` is making it harder for me to understand what is actually going on. Can we just maybe remove it? 

The error here was that I was trying to write a file that already exists. Instead of giving me this error I got the uninformative "Error occured during writing JSONL file" message.

### PR DESCRIPTION
**Pull request by samarpan-rai**
Should fix #52

### CODE REVIEW

**Comment by koaning** [comment]
Did you remove all of them? I think we also want to remove the ones in the `write_*` functions.

**Comment by koaning** [comment]
Once this change is in I'll make a new release :)

**Comment by samarpan-rai** [comment]
> Did you remove all of them? I think we also want to remove the ones in the `write_*` functions.

Issue #52 only specified jsonl so I didn't remove the ones in json. It should be done now. I should really learn to not over-engineer stuff 😅

**Comment by koaning** [comment]
LGTM!

**Pull request merged**
